env:
  GITHUB_TOKEN: ENCRYPTED[1c2ef2877c7f171e40a831f61367e810b57010d6b2eded04f68177e3ec096c3c85619be02f3f0c081fd1eb9b64dd15bb]

macos_universal_task:
  macos_instance:
    image: big-sur-xcode
  env:
    RUST_HOME: $HOME/macos
    CARGO_HOME: $RUST_HOME/cargo
    RUSTUP_HOME: $RUST_HOME/rustup
    PATH: $CARGO_HOME/bin:$PATH
  rust_cache:
    folder: $RUST_HOME
    reupload_on_changes: true
    fingerprint_script:
      - echo $CIRRUS_OS
      - date +%Y
    populate_script: >
      curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs |
      sh -s -- -y --verbose --no-modify-path --target aarch64-apple-darwin
  update_script: rustup --verbose update
  target_cache:
    folder: target
    reupload_on_changes: true
    fingerprint_script:
      - echo $CIRRUS_OS
      - rustc --version
  build_script:
    - cargo build --verbose --release --target aarch64-apple-darwin
    - mv target/aarch64-apple-darwin/release/yj yj.macos.aarch64
    - cargo build --verbose --release --target x86_64-apple-darwin
    - mv target/x86_64-apple-darwin/release/yj yj.macos.x86_64
    - lipo -create -output yj.macos.universal yj.macos.aarch64 yj.macos.x86_64
    - file yj.macos.universal
  binary_artifacts:
    path: yj.macos.*
  release_script: ./upload-binary.sh yj.macos.*
  before_cache_script: rm -f target/.rustc_info.json

linux_x68_64_task:
  container:
    image: rust:alpine
  registry_cache:
    folder: $CARGO_HOME/registry
    reupload_on_changes: true
    fingerprint_script: date +%Y
  target_cache:
    folder: target
    reupload_on_changes: true
    fingerprint_script:
      - echo $CIRRUS_OS
      - rustc --version
  setup_script:
    - apk add --no-cache libc-dev
  build_script:
    - cargo build --verbose --release
    - mv target/release/yj yj.$CIRRUS_OS.x86_64
    - ldd yj.$CIRRUS_OS.x86_64 || echo yay - statically linked
  binary_artifacts:
    path: yj.$CIRRUS_OS.*
  release_script: ./upload-binary.sh yj.$CIRRUS_OS.*
  before_cache_script: rm -f target/.rustc_info.json

freebsd_x86_task:
  freebsd_instance:
    image_family: freebsd-12-2
  env:
    RUST_HOME: $HOME/freebsd
    CARGO_HOME: $RUST_HOME/cargo
    RUSTUP_HOME: $RUST_HOME/rustup
    PATH: $CARGO_HOME/bin:$PATH
  rust_cache:
    folder: $RUST_HOME
    reupload_on_changes: true
    fingerprint_script:
      - echo $CIRRUS_OS
      - date +%Y
    populate_script: >
      curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs |
      sh -s -- -y --verbose --no-modify-path
  update_script: rustup --verbose update
  target_cache:
    folder: target
    reupload_on_changes: true
    fingerprint_script:
      - echo $CIRRUS_OS
      - rustc --version
  build_script:
    - cargo build --verbose --release
    - mv target/release/yj yj.$CIRRUS_OS.x86_64
    - file yj.$CIRRUS_OS.x86_64
  binary_artifacts:
    path: yj.$CIRRUS_OS.*
  release_script: ./upload-binary.sh yj.$CIRRUS_OS.*
  before_cache_script: rm -f target/.rustc_info.json

windows_x86_task:
  windows_container:
    image: cirrusci/windowsservercore:2019
  env:
    RUST_HOME: C:\Users\ContainerAdministrator\rust
    CARGO_HOME: $RUST_HOME\cargo
    RUSTUP_HOME: $RUST_HOME\rustup
    PATH: $CARGO_HOME\bin;$PATH
  vs_cpp_script:
    - curl -fSLo vs_buildtools.exe https://aka.ms/vs/16/release/vs_buildtools.exe
    - >
      vs_buildtools.exe --quiet --wait --norestart --nocache
      --installPath C:\BuildTools
      --add Microsoft.Component.MSBuild
      --add Microsoft.VisualStudio.Component.Windows10SDK.18362
      --add Microsoft.VisualStudio.Component.VC.Tools.ARM64
      --add Microsoft.VisualStudio.Component.VC.Tools.x86.x64
  rust_cache:
    folder: $RUST_HOME
    reupload_on_changes: true
    fingerprint_script:
      - echo %CIRRUS_OS%
      - echo plusarm
      - date /t
    populate_script:
      - curl -fSLo rustup-init.exe https://win.rustup.rs/x86_64
      - rustup-init.exe -y --verbose --target aarch64-pc-windows-msvc
      - del rustup-init.exe
  update_script:
    - rustup --verbose update
  target_cache:
    folder: target
    reupload_on_changes: true
    fingerprint_script:
      - echo %CIRRUS_OS%
      - rustc --version
  build_script:
    - cargo build --verbose --release --target aarch64-pc-windows-msvc
    - move target\aarch64-pc-windows-msvc\release\yj.exe yj.%CIRRUS_OS%.aarch64.exe
    - cargo build --verbose --release --target x86_64-pc-windows-msvc
    - move target\x86_64-pc-windows-msvc\release\yj.exe yj.%CIRRUS_OS%.x86_64.exe
  binary_artifacts:
    path: yj.%CIRRUS_OS%.*
  before_cache_script: del target\.rustc_info.json
